export const pets = [
  {
    id: 1,
    image: "/pet-hero.jpg",
    name: "Milo",
    type: "Golden Retriever",
    age: "2 years",
    gender: "Male",
    location: "Dhaka",
    fee: "$120",
  },
  {
    id: 2,
    image: "/pet-hero.jpg",
    name: "Luna",
    type: "Persian Cat",
    age: "1 year",
    gender: "Female",
    location: "Chattogram",
    fee: "$150",
  },
  {
    id: 3,
    image: "/pet-hero.jpg",
    name: "Coco",
    type: "Italian Turtle",
    age: "3 years",
    gender: "Female",
    location: "Sylhet",
    fee: "$110",
  },
  {
    id: 4,
    image: "/pet-hero.jpg",
    name: "Bella",
    type: "Golden Retriever",
    age: "4 years",
    gender: "Female",
    location: "Rajshahi",
    fee: "$130",
  },
  {
    id: 5,
    image: "/pet-hero.jpg",
    name: "Rocky",
    type: "Siberian Husky",
    age: "3 years",
    gender: "Male",
    location: "Khulna",
    fee: "$140",
  },
  {
    id: 6,
    image: "/pet-hero.jpg",
    name: "Penny",
    type: "Tabby Cat",
    age: "10 months",
    gender: "Female",
    location: "Barishal",
    fee: "$100",
  },
  {
    id: 7,
    image: "/pet-hero.jpg",
    name: "Bruno",
    type: "French Bulldog",
    age: "5 years",
    gender: "Male",
    location: "Mymensingh",
    fee: "$160",
  },
  {
    id: 8,
    image: "/pet-hero.jpg",
    name: "Nina",
    type: "Calico Cat",
    age: "2 years",
    gender: "Female",
    location: "Cumilla",
    fee: "$125",
  },
];
